### ISSUE TITLE
Resize doesn't capture new position

### ISSUE THREAD

**Issue by natew** [tmandry/Swindler#11]
With this setup, I don't see any updated value output while dragging from the edge of a window to resize it. The size changes, but the position isn't updated.

![image](https://user-images.githubusercontent.com/12100/39090111-7f3e22de-458a-11e8-9431-1dee15568564.png)

**Comment by tmandry** [comment]
Thanks for the report! I am merging a fix, finally.

I'm beginning to think that separating out position and size, like the AX APIs do, is the wrong model. These two things can change simultaneously, which should be handled as one event.
