### ISSUE TITLE
Upgrade to PromiseKit 6

### ISSUE THREAD

**Issue by tmandry** [tmandry/Swindler#17]
PromiseKit 6 renames a bunch of things to fix the annoying type annotations needed everywhere. That definitely needs to be passed on to users of Swindler.

**Comment by IgorMuzyka** [comment]
<img width="1440" alt="screen shot 2018-11-09 at 18 15 44" src="https://user-images.githubusercontent.com/4402333/48274220-803d9600-e44b-11e8-9945-7ae8def366e8.png">
<img width="1440" alt="screen shot 2018-11-09 at 18 15 49" src="https://user-images.githubusercontent.com/4402333/48274224-82075980-e44b-11e8-80bf-65861c2dd65f.png">
Would really appreciate update as i wanted to build a little app using your library but got stuck as soon as installing dependencies.

**Comment by tmandry** [comment]
@IgorMuzyka Thanks for your feedback! Hoping to get to this soon, once I fix #24.
