### ISSUE TITLE
Is it possible to get value of kCGWindowNumber of window?

### ISSUE THREAD

**Issue by ukushu** [tmandry/Swindler#64]
I have tried to find it in code, but I see no way for getting it. 
Maybe you can help me?

**Comment by CoderLeonidas** [comment]
It seems that Apple won't let us do that. It's relevant to Apple's Security or Design Role

**Comment by ukushu** [comment]
Even if you have full privileges and all sort of security blockers is disabled for the app?

**Comment by tmandry** [comment]
The links in this comment might be helpful: https://github.com/tmandry/x3/issues/1#issuecomment-437231522
