### ISSUE TITLE
Docs seem to be out of date (Podfile missing)

### ISSUE THREAD

**Issue by chrispaynter** [tmandry/Swindler#69]
Howdy, just followed the instructions to set this up locally and noticed the Podfile has been removed in [993139b0f3ee575ded26fae31434bd0d43e1eeb3](https://github.com/tmandry/Swindler/commit/993139b0f3ee575ded26fae31434bd0d43e1eeb3)

I'm guessing some restructuring is being done to the project but the documentation hasn't yet been updated.

The API looks good, and wanted to trial using it in a new project.

**Comment by chrispaynter** [comment]
I've created a PR to update the Readme - https://github.com/tmandry/Swindler/pull/70

**Comment by tmandry** [comment]
Closed in #70
