### ISSUE TITLE
Cannot be added as a Swift Package

### ISSUE THREAD

**Issue by chrispaynter** [tmandry/Swindler#71]
I tried to add Swindler as a package via Xcode as per [their docs](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app).

Due to AXSwift being a locally referenced package,[ it's not possible to do so.](https://stackoverflow.com/a/64020464)

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1684083/102712407-d2f40800-42c9-11eb-88f6-f8a5413788ce.png">

I forked and created a branch that sets the path correctly and it installs correctly into Xcode - https://github.com/chrispaynter/Swindler/tree/hotfix/change-axswift-reference

I'm guessing you're using submodules for ease of debugging / development of AXSwift.

Might be good to add some extra documentation to the readme about setting up Swindler as a dependency.

Understandably, Swindler is still alpha. Might be worth looking at what versioned (non `master` branch) package references might look like moving forward.

**Comment by tmandry** [comment]
Thanks for the report. I'm removing the submodule in #72 and will release a new version soon.
