### ISSUE TITLE
Move window to another desktop

### ISSUE THREAD

**Issue by ziulev** [tmandry/Swindler#81]
I could not find in the documentation
how to move a window from one desktop to another?

I can do `window.frame.set(...`
But this only works within the current desktop

**Comment by tmandry** [comment]
Just to make sure, do you mean another space, or to another screen?

Moving windows between spaces requires private APIs which I haven't used yet. I think we could make this an optional feature of the library. See also https://github.com/tmandry/Swindler/pull/78#issuecomment-864697597.

**Comment by ziulev** [comment]
I mean to another space,
Ok, thank you for the answer
